In [2]:
import tensorflow as tf

In [9]:
import numpy as np

In [14]:
arr_list = np.arange(0,100).astype(np.float32)
shape = arr_list.shape
dataset = tf.data.Dataset.from_tensor_slices(arr_list)
dataset_iterator = dataset.shuffle(shape[0]).batch(10)
def model(xs):
    outputs = tf.multiply(xs,0.1)
    return outputs
for it in dataset_iterator:
    logits = model(it)
    print(logits)

tf.Tensor(
[7.2000003 5.9       6.2000003 6.7000003 0.5       9.7       6.
 3.1000001 0.8       4.9      ], shape=(10,), dtype=float32)
tf.Tensor(
[1.       6.6      8.8      9.       4.       2.       9.400001 7.9
 6.3      2.8     ], shape=(10,), dtype=float32)
tf.Tensor(
[3.2       2.9       7.7000003 8.3       5.        2.7       5.6
 5.2000003 9.8       2.3      ], shape=(10,), dtype=float32)
tf.Tensor(
[6.9       3.9       9.5       2.4       9.2       5.1       3.6000001
 1.1       7.6       7.5      ], shape=(10,), dtype=float32)
tf.Tensor(
[5.7000003 0.7       6.1       8.400001  9.900001  4.8       6.8
 0.        3.4       7.8      ], shape=(10,), dtype=float32)
tf.Tensor(
[1.8000001  8.         3.7        0.6        6.5        2.1000001
 9.1        0.90000004 2.2        4.6       ], shape=(10,), dtype=float32)
tf.Tensor(
[7.3       1.7       0.4       2.5       5.4       5.3       0.2
 4.3       1.3000001 0.1      ], shape=(10,), dtype=float32)
tf.Tensor(
[6.4       9.6     

In [17]:
import tensorflow as tf


vector = tf.constant([4,5,6], dtype=tf.float32)
eucNorm = tf.norm(vector, ord="euclidean")

# sess = tf.Session()
sess.run(eucNorm)


NameError: name 'sess' is not defined